name: ancient_game
description: "Ancient Themed Game" 
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  platform: ^3.0.0
  flame: ^1.13.1
  flame_tiled: any
  flame_audio: any
  flame_forge2d: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: joystix monospace
      fonts: 
        - asset: fonts/joystix monospace.otf

  assets:
    - assets/tiles/
    - assets/images/
    - assets/images/sprites/
    - assets/images/sprites/player/
    - assets/images/tilesets/